name: slot_package
description: A new Flutter package project.
version: 0.0.1


environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  auto_size_text: ^3.0.0
  flame: 1.6.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
