name: slot_package
description: A new Flutter package project.
version: 0.0.1


environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/avatar.png
    - assets/hero.png
    - assets/lineup.png
    - assets/explore1.png
    - assets/explore2.png
    - assets/explore.png

    - assets/interests/basketball.png
    - assets/interests/football.png
    - assets/interests/soccer.png
    - assets/interests/baseball.png
    - assets/interests/tennis.png

    - assets/categories/badminton.png
    - assets/categories/pingpong.png
    - assets/categories/baseball.png
    - assets/categories/basketball.png
    - assets/categories/football.png
    - assets/categories/soccer.png
    - assets/categories/tennis.png
    - assets/categories/volly.png

    - assets/clubs/barcelona.png
    - assets/clubs/realmadrid.png

    - assets/leagues/premier.png
    - assets/leagues/laliga.png
